library(mice)
library(caTools)
library(Rcpp)
library(ROCR)
library(rpart)
setwd("C:\\Users\\Shantanu\\Desktop\\analytics_edge")
data<-read.csv(file= "AirlinesCluster.csv")
summary(data)
library(e1071)
library(caret)
preproc=preProcess(data)
data_norm=predict(preproc, data)
distance=dist(data_norm, method="euclidean")
cluster=hclust(distance,method="ward.D")
plot(cluster)
clustergrp=cutree(cluster,k=5)
plot(clustergrp)
tapply(data_norm$Balance,clustergrp,mean)
set.seed(123)
km=kmeans(data_norm,centers=5,iter.max=1000)
summary(km)
table(km$cluster,data_norm$Balance)
