library(mice)
library(caTools)
library(Rcpp)
library(ROCR)
library(rpart)
setwd("\\home\\work\\analytics_edge")
data<-read.csv(file= "census.csv")
summary(data)
set.seed(4567)
spl=sample.split(data$over50k,0.6)
train=subset(data,spl==TRUE)
test=subset(data,spl==FALSE)
logit=glm(over50k~.,data=train, family="binomial")
summary(logit)
pred=predict(logit,newdata=test,type="response")
table(test$over50k,pred>0.5)
Rocpred=prediction(pred,test$over50k)
as.numeric(performance(Rocpred,"auc")@y.values)
table(test$over50k)
library(rpart)
tree=rpart(train$over50k~.,data=train,method="class")
library(rpart.plot)
prp(tree)
predtree=predict(tree,newdata=test)
table(predtree[,2],test$over50k)
rocpred=prediction(predtree[,2],test$over50k)
as.numeric(performance(rocpred,"auc")@y.values)
set.seed(234)
trainSmall = train[sample(nrow(train), 2000), ]
set.seed(234)
library(randomForest)
forest=randomForest(over50k~.,data=trainSmall)
predfor=predict(forest,newdata=test,type="prob")
rocpredfor=prediction(predfor[,2],test$over50k)
as.numeric(performance(rocpredfor,"auc")@y.values)
varImpPlot(forest)

library(e1071)
library(caret)
cpgrid=expand.grid(.cp=seq(0.002,0.1,0.002))
set.seed(321)
numfolds=trainControl(method="cv",number=10)
train(over50k~.,data=train,method="rpart",trControl=numfolds,tuneGrid=cpgrid)
treecv=rpart(over50k~.,data=train,method="class",cp=0.002)
pred=predict(treecv,newdata=test,type="class")
table(test$over50k,pred)
library(rpart.plot)
prp(treecv)
